name: example-workflow
on: [push]
jobs:
  hello_world:
    if: github.repository == 'Vador92/actions-learning'
    runs-on: ubuntu-latest
    steps:
      - name: "Hello World"
        run: echo "Hello World!"
  goodbye-moon:
    runs-on: ubuntu-latest
    steps:
      - name: "Goodbye moon"
        run: echo "Goodbye Moon!"