name: "Webhook event example"

on:
    repository_dispatch:
        types:
            - custom_webhook

jobs:
    respond-to-dispatch:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
            - name: Run a script
              run: |
                echo "Event name: ${{ github.event_name }}"
                echo "Action type: ${{ github.event.action }}"
